version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=supersecret
    ports:
      - "5433:5432"

volumes:
  db-vol:
