// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestSampleTable struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	IntExample  *int32           `json:"intExample"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	DeletedAt   pgtype.Timestamp `json:"deletedAt"`
}
